name: Close Published Issue

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to close after publishing'
        required: true
        type: string
      post_file:
        description: 'Published post filename'
        required: true
        type: string
      engagement_metrics:
        description: 'Optional engagement metrics (likes, comments, shares)'
        required: false
        type: string
        default: ''

jobs:
  close-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update project status to Published
        run: |
          # Get the project item ID for this issue
          ITEM_ID=$(gh api graphql -f query='
            query($issue: Int!, $owner: String!, $repo: String!) {
              repository(owner: $owner, name: $repo) {
                issue(number: $issue) {
                  projectItems(first: 10) {
                    nodes {
                      id
                      project {
                        number
                      }
                    }
                  }
                }
              }
            }
          ' -F issue=${{ inputs.issue_number }} -F owner="${{ github.repository_owner }}" -F repo="${{ github.event.repository.name }}" --jq '.data.repository.issue.projectItems.nodes[] | select(.project.number == 3) | .id')
          
          if [ -n "$ITEM_ID" ]; then
            echo "Updating project item to Published status"
            # Update status to Published
            gh api graphql -f query='
              mutation($itemId: ID!, $statusId: String!) {
                updateProjectV2ItemFieldValue(
                  input: {
                    projectId: "PVT_kwHOACRKHs4A-6uX"
                    itemId: $itemId
                    fieldId: "PVTSSF_lAHOACRKHs4A-6uXzgyLTcw"
                    value: { singleSelectOptionId: $statusId }
                  }
                ) {
                  projectV2Item {
                    id
                  }
                }
              }
            ' -f itemId="$ITEM_ID" -f statusId="eb4dcd9a"
          else
            echo "Issue not found in project"
          fi
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Close issue with publication confirmation
        run: |
          COMMENT_BODY="🎉 Post has been successfully published to LinkedIn!
          
          **Published File**: \`${{ inputs.post_file }}\`
          **Status**: ✅ Published
          **Date**: $(date +'%Y-%m-%d %H:%M:%S UTC')
          "
          
          # Add engagement metrics if provided
          if [ -n "${{ inputs.engagement_metrics }}" ]; then
            COMMENT_BODY="$COMMENT_BODY
          
          **Engagement Metrics**: ${{ inputs.engagement_metrics }}"
          fi
          
          COMMENT_BODY="$COMMENT_BODY
          
          ---
          This issue is now closed as the content has been successfully published."
          
          # Add comment to issue
          gh issue comment ${{ inputs.issue_number }} --body "$COMMENT_BODY"
          
          # Close the issue
          gh issue close ${{ inputs.issue_number }} --reason completed
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Update project card (if exists)
        continue-on-error: true
        run: |
          # This step will update the project card status to "Published"
          # when GitHub Projects are set up
          echo "Project card update will be implemented when project is created"